### PR TITLE
Update `README`

### PR DESCRIPTION
**Pull request by lippserd**

### CODE REVIEW

**Comment by lippserd** [comment]
@martialblog In our last discussion, you had some considerations regarding the topics of installation, vision, and roadmap. I've tried to incorporate those in this PR and would appreciate your feedback.

**Comment by lippserd** [comment]
@jhoxhaa @Jan-Schuppik Please add new screenshots to this PR. Afterwards please commit the same changes to https://github.com/Icinga/icinga-kubernetes.

**Comment by martialblog** [comment]
@lippserd Vision and Roadmap are a good idea. 

I think it would also make sense to add a hint, that users should use the latest snapshot build instead of the current v0.1.0 -  that might also avoid unnecessary issues being opened.

**Comment by lippserd** [comment]
> I think it would also make sense to add a hint, that users should use the latest snapshot build instead of the current v0.1.0 - that might also avoid unnecessary issues being opened.

Version 0.2.0 is coming out this week, so I'll skip this.

**Pull request merged**
